### ISSUE TITLE
k-means: support for custom sample function

### ISSUE THREAD

**Issue by FunkMonkey** [Yomguithereal/talisman#47]
Feature request for passing a optional custom `sample` function (used for randomizing first centroids) via options. It is useful for creating reproducable results by having a `sample` function that uses a pseudo random number generator instead of `Math.random` which is used by `lodash/sample`.

What do you think?

**Comment by Yomguithereal** [comment]
Hello @FunkMonkey. This is a good idea indeed. I will implement it soon. However, I will also refactor the function as a whole and reorder some arguments to better fit the functional paradigm of the library so expect some slight API changes.

Do you have an opinion concerning the signature of the sampling function? Like what should we pass it and what it should return?

**Comment by Yomguithereal** [comment]
Here is what I propose:

```js
function kMeans(options, data)

// options:
// options.k: nb of clusters (defaults to 8)
// options.distance: distance function (defaults to euclidean distance)
// options.maxIterations: maximum nb of iterations (defaults to 300)
```

The function will also use a class, under the hood, so people can fine tune the usage of the algorithm by running iterations asynchronously etc & display some results live etc.

**Comment by FunkMonkey** [comment]
@Yomguithereal Your proposal looks good!

Concerning the sample function, there are multiple possibilities:
1. pass a function via `options.sample`, which has the same signature as `lodash/sample` (only array as parameter). Use `lodash/sample` if no sample function provided via `options.sample`.
2. pass a function via `options.rng`, which returns a number between `0` and `1` and implement your own sample function with the following signature: `sample( rng, array )`. Use `Math.random` if `options.rng` not provided.

I thinks 1. is the better option as people may want a sample function that is not random at all, but makes a good first guess...

**Comment by Yomguithereal** [comment]
I also prefer 1. because 2. can be achieved by using 1. and not the other way around. So, let me sum this up:

Let's call the options `centroids` or `initialCentroids` or `init` to match scikit-learn's terminology.

And either you can pass the array of centroids, or a function taking the dataset as argument and having to return the array of centroids.

Does it work for you?

**Comment by FunkMonkey** [comment]
Well that's a good idea, too. I just thought of the `sample` function as it was used in [line 63](https://github.com/Yomguithereal/talisman/blob/master/src/clustering/k-means.js#L63), but getting all centroids is even better. `initialCentroids` sounds best. The function would obviously also need `k` as a parameter, too...

**Comment by Yomguithereal** [comment]
Ok, I'm starting to refactor this. Expect a new version in the afternoon.

**Comment by Yomguithereal** [comment]
Just released v0.11.0 with the updated API. Updates docs [here](http://yomguithereal.github.io/talisman/clustering#k-means). Thanks @FunkMonkey.

**Comment by FunkMonkey** [comment]
@Yomguithereal Cool. I'll check it out end of next week. Thanks a lot!

A couple of things, though...
- Why must the `initialCentroids` be of length `this.dimensions` instead of `k` as it was before? See line [97](https://github.com/Yomguithereal/talisman/blob/master/src/clustering/k-means.js#L97)
- If clusters have no items, a non-customizable random number generator will be used, `lodash/sampleSize` (line [153](https://github.com/Yomguithereal/talisman/blob/master/src/clustering/k-means.js#L153))
- Concerning the functional paradigm, the `initialCentroids` function should get `options` first - not that it matters in this case as both parameters are always supplied anyway :)

**Comment by Yomguithereal** [comment]
Hello @FunkMonkey 

* This is indeed a bug. Thanks for noticing.
* I'll take your insight concerning the second point. How do implementations in other languages usually handle the empty cluster case?
* That's indeed true. I will probably reverse those soon.

**Comment by Yomguithereal** [comment]
I've committed a fix for the first problem. I'll wait a bit before releasing a new version depending on what we decide for subsequent points.

**Comment by FunkMonkey** [comment]
@Yomguithereal 
> I'll take your insight concerning the second point. How do implementations in other languages usually handle the empty cluster case?

uh. I am by no means a k-means expert, so I really don't know how other implementations handle the case! ;) There is a [thread on Stackovervlow](http://stackoverflow.com/questions/11075272/k-means-empty-cluster), where this topic is discussed. The options are basically: 
- ignore empty clusters, thus k-means may return less than `k` clusters. Results may be better this way, but users may be expecting exactly `k` clusters
- choose random elements for empty clusters (as you do right now)

I guess there is a case for both variants, so maybe there should be an option like `ignoreEmptyClusters`. Don't know how much the algorithm needs to be adapted for that. For my personal case: I can totally live with choosing a random element, I just need that element being chosen using my custom random number generator instead of `lodash/sampleSize`. So for real deterministic behaviour, I would need to provide a `options.sampleSize`. To make it more useful and in line with `initialCentroids` though, I'd name it `options.inializeEmptyCluster` and the user can thus decide on his/her own how to fill this cluster (e.g. choosing the closest value to the current centroid or something like that). 

Looking at the code, there is a bug anyway: choosing a random sample and adding it to the empty cluster may result in this sample being in multiple clusters if it was the last iteration as it happens at the end of the iteration...

Anyway, thanks a lot for your quick responses and changes :)

**Comment by Yomguithereal** [comment]
Ok, I will try to fix this & to add a relevant option.

**Comment by Yomguithereal** [comment]
So @FunkMonkey, I added a `sampler` option that takes a function of same signature as lodash/sampleSize and fixed the vector in multiple clusters issue. I also added a safeguard that will throw if you try to cluster less vectors than the provided k. Now, could you try the last version of master to see if it fits you and if so, I will release a new version on npm.

Also, if would be glad to see a very simplified version of the datasets you're working on because they could provide the library with some meaningful unit tests for the sampler & initialCentroids options.

**Comment by FunkMonkey** [comment]
Great, thank you! I'll try it out at the beginning of next week and I'll see how to simplify my dataset.

Looking at the code, I still see 3 bugs though:
- [L106](https://github.com/Yomguithereal/talisman/blob/master/src/clustering/k-means.js#L106): still using `dimensions` here instead of `k`. Isn't your unit test failing here because of line [114](https://github.com/Yomguithereal/talisman/blob/master/src/clustering/k-means.js#L114)?
- [L169](https://github.com/Yomguithereal/talisman/blob/master/src/clustering/k-means.js#L169): `sampler` returns an array, thus the vector is the first element and not the complete result
- [L170](https://github.com/Yomguithereal/talisman/blob/master/src/clustering/k-means.js#L170): need to `push` into `displacedVectors`, too

Thanks a lot again!

**Comment by Yomguithereal** [comment]
Thanks for the review @FunkMonkey. I just committed a fix according to your remarks.
